clox: main.c memory.c chunk.c debug.c value.c vm.c scanner.c compiler.c
	gcc -o clox main.c memory.c chunk.c debug.c value.c vm.c scanner.c compiler.c -I.

debug: main.c memory.c chunk.c debug.c value.c vm.c scanner.c compiler.c
	gcc -O0 -g -o debug main.c memory.c chunk.c debug.c value.c vm.c scanner.c compiler.c -I.